# Generated by Django 4.2.3 on 2023-11-09 21:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="repository",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.FileField(blank=True, upload_to="project_images/"),
        ),
        migrations.AlterField(
            model_name="project",
            name="technology",
            field=models.CharField(max_length=100),
        ),
    ]
